export const underGround = {
  numRows: 29,
  numCols: 11,

  rowData: [
    {
      type: "fixed",
      rowSpan: 8,
      colSpan: 4,
      label: "File Compactors",
      disabled: true,
      floor: "UG",
      seriesNo: 0,
    },
    {
      type: "path",
      rowSpan: 29,
      colSpan: 1,
      floor: "UG",
      seriesNo: 1,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "UG_S1",
      floor: "UG",
      seriesNo: 2,
    },
    {
      type: "small",
      colSpan: 3,
      seatId: "UG_S2",
      floor: "UG",
      seriesNo: 3,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 6,
      floor: "UG",
      seriesNo: 4,
    },
    {
      type: "small",
      colSpan: 2,
      seatId: "UG_S3",
      floor: "UG",
      seriesNo: 5,
    },
    {
      type: "small",
      colSpan: 2,
      seatId: "UG_S4",
      floor: "UG",
      seriesNo: 6,
    },
    {
      type: "small",
      colSpan: 2,
      seatId: "UG_S5",
      floor: "UG",
      seriesNo: 7,
    },
    {
      type: "small",
      colSpan: 2,
      seatId: "UG_S6",
      floor: "UG",
      seriesNo: 8,
    },
    {
      type: "small",
      colSpan: 2,
      seatId: "UG_S7",
      floor: "UG",
      seriesNo: 9,
    },
    {
      type: "small",
      colSpan: 2,
      seatId: "UG_S8",
      floor: "UG",
      seriesNo: 10,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 6,
      floor: "UG",
      seriesNo: 11,
    },
    {
      type: "small",
      colSpan: 2,
      seatId: "UG_S9",
      floor: "UG",
      seriesNo: 12,
    },
    {
      type: "small",
      colSpan: 2,
      seatId: "UG_S10",
      floor: "UG",
      seriesNo: 13,
    },
    {
      type: "small",
      colSpan: 2,
      seatId: "UG_S11",
      floor: "UG",
      seriesNo: 14,
    },
    {
      type: "small",
      colSpan: 2,
      seatId: "UG_S12",
      floor: "UG",
      seriesNo: 15,
    },
    {
      type: "small",
      colSpan: 2,
      seatId: "UG_S13",
      floor: "UG",
      seriesNo: 16,
    },
    {
      type: "small",
      colSpan: 2,
      seatId: "UG_S14",
      floor: "UG",
      seriesNo: 17,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 6,
      floor: "UG",
      seriesNo: 18,
    },
    {
      type: "small",
      seatId: "UG_S15",
      floor: "UG",
      seriesNo: 19,
    },
    {
      type: "small",
      seatId: "UG_S16",
      floor: "UG",
      seriesNo: 20,
    },
    {
      type: "small",
      seatId: "UG_S17",
      floor: "UG",
      seriesNo: 21,
    },
    {
      type: "small",
      seatId: "UG_S18",
      floor: "UG",
      seriesNo: 22,
    },
    {
      type: "block",
      rowSpan: 3,
      colSpan: 6,
      seatId: "UG_B1",
      floor: "UG",
      seriesNo: 23,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 4,
      floor: "UG",
      seriesNo: 24,
    },
    {
      type: "small",
      seatId: "UG_S19",
      floor: "UG",
      seriesNo: 25,
    },
    {
      type: "small",
      seatId: "UG_S20",
      floor: "UG",
      seriesNo: 26,
    },
    {
      type: "small",
      seatId: "UG_S21",
      floor: "UG",
      seriesNo: 27,
    },
    {
      type: "small",
      seatId: "UG_S22",
      floor: "UG",
      seriesNo: 28,
    },
    {
      type: "small",
      seatId: "UG_S23",
      floor: "UG",
      seriesNo: 29,
    },
    {
      type: "small",
      seatId: "UG_S24",
      floor: "UG",
      seriesNo: 30,
    },
    {
      type: "small",
      seatId: "UG_S25",
      floor: "UG",
      seriesNo: 31,
    },
    {
      type: "small",
      seatId: "UG_S26",
      floor: "UG",
      seriesNo: 32,
    },
    {
      type: "block",
      rowSpan: 3,
      colSpan: 6,
      seatId: "UG_B2",
      floor: "UG",
      seriesNo: 33,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 4,
      floor: "UG",
      seriesNo: 34,
    },
    {
      type: "small",
      seatId: "UG_S27",
      floor: "UG",
      seriesNo: 35,
    },
    {
      type: "small",
      seatId: "UG_S28",
      floor: "UG",
      seriesNo: 36,
    },
    {
      type: "small",
      seatId: "UG_S29",
      floor: "UG",
      seriesNo: 37,
    },
    {
      type: "small",
      seatId: "UG_S30",
      floor: "UG",
      seriesNo: 38,
    },
    {
      type: "small",
      seatId: "UG_S31",
      floor: "UG",
      seriesNo: 39,
    },
    {
      type: "small",
      seatId: "UG_S32",
      floor: "UG",
      seriesNo: 40,
    },
    {
      type: "small",
      seatId: "UG_S33",
      floor: "UG",
      seriesNo: 41,
    },
    {
      type: "small",
      seatId: "UG_S34",
      floor: "UG",
      seriesNo: 42,
    },
    {
      type: "block",
      rowSpan: 3,
      colSpan: 6,
      seatId: "UG_B3",
      floor: "UG",
      seriesNo: 43,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 4,
      floor: "UG",
      seriesNo: 44,
    },
    {
      type: "small",
      seatId: "UG_S35",
      floor: "UG",
      seriesNo: 45,
    },
    {
      type: "small",
      seatId: "UG_S36",
      floor: "UG",
      seriesNo: 46,
    },
    {
      type: "small",
      seatId: "UG_S37",
      floor: "UG",
      seriesNo: 47,
    },
    {
      type: "small",
      seatId: "UG_S38",
      floor: "UG",
      seriesNo: 48,
    },
    {
      type: "small",
      seatId: "UG_S39",
      floor: "UG",
      seriesNo: 49,
    },
    {
      type: "small",
      seatId: "UG_S40",
      floor: "UG",
      seriesNo: 50,
    },
    {
      type: "small",
      seatId: "UG_S41",
      floor: "UG",
      seriesNo: 51,
    },
    {
      type: "small",
      seatId: "UG_S42",
      floor: "UG",
      seriesNo: 52,
    },
    {
      type: "fixed",
      rowSpan: 3,
      colSpan: 6,
      label: "Medical Room",
      disabled: true,
      floor: "UG",
      seriesNo: 53,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 4,
      floor: "UG",
      seriesNo: 54,
    },
    {
      type: "small",
      seatId: "UG_S43",
      floor: "UG",
      seriesNo: 55,
    },
    {
      type: "small",
      seatId: "UG_S44",
      floor: "UG",
      seriesNo: 56,
    },
    {
      type: "small",
      seatId: "UG_S45",
      floor: "UG",
      seriesNo: 57,
    },
    {
      type: "small",
      seatId: "UG_S46",
      floor: "UG",
      seriesNo: 58,
    },
    {
      type: "small",
      seatId: "UG_S47",
      floor: "UG",
      seriesNo: 59,
    },
    {
      type: "small",
      seatId: "UG_S48",
      floor: "UG",
      seriesNo: 60,
    },
    {
      type: "small",
      seatId: "UG_S49",
      floor: "UG",
      seriesNo: 61,
    },
    {
      type: "small",
      seatId: "UG_S50",
      floor: "UG",
      seriesNo: 62,
    },
    {
      type: "small",
      colSpan: 2,
      seatId: "UG_S51",
      floor: "UG",
      seriesNo: 63,
    },
    {
      type: "small",
      colSpan: 2,
      seatId: "UG_S52",
      floor: "UG",
      seriesNo: 64,
    },
    {
      type: "small",
      colSpan: 2,
      seatId: "UG_S53",
      floor: "UG",
      seriesNo: 65,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 4,
      floor: "UG",
      seriesNo: 66,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 6,
      floor: "UG",
      seriesNo: 67,
    },
    {
      type: "small",
      seatId: "UG_S54",
      floor: "UG",
      seriesNo: 68,
    },
    {
      type: "small",
      seatId: "UG_S55",
      floor: "UG",
      seriesNo: 69,
    },
    {
      type: "small",
      seatId: "UG_S56",
      floor: "UG",
      seriesNo: 70,
    },
    {
      type: "small",
      seatId: "UG_S57",
      floor: "UG",
      seriesNo: 71,
    },
    {
      type: "small",
      colSpan: 2,
      seatId: "UG_S58",
      floor: "UG",
      seriesNo: 72,
    },
    {
      type: "small",
      colSpan: 2,
      seatId: "UG_S59",
      floor: "UG",
      seriesNo: 73,
    },
    {
      type: "small",
      colSpan: 2,
      seatId: "UG_S60",
      floor: "UG",
      seriesNo: 74,
    },
    {
      type: "small",
      seatId: "UG_S61",
      floor: "UG",
      seriesNo: 75,
    },
    {
      type: "small",
      seatId: "UG_S62",
      floor: "UG",
      seriesNo: 76,
    },
    {
      type: "small",
      seatId: "UG_S63",
      floor: "UG",
      seriesNo: 77,
    },
    {
      type: "small",
      seatId: "UG_S64",
      floor: "UG",
      seriesNo: 78,
    },
    {
      type: "small",
      colSpan: 2,
      seatId: "UG_S65",
      floor: "UG",
      seriesNo: 79,
    },
    {
      type: "small",
      colSpan: 2,
      seatId: "UG_S66",
      floor: "UG",
      seriesNo: 80,
    },
    {
      type: "small",
      colSpan: 2,
      seatId: "UG_S67",
      floor: "UG",
      seriesNo: 81,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 4,
      floor: "UG",
      seriesNo: 82,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 6,
      floor: "UG",
      seriesNo: 83,
    },
    {
      type: "small",
      seatId: "UG_S68",
      floor: "UG",
      seriesNo: 84,
    },
    {
      type: "small",
      seatId: "UG_S69",
      floor: "UG",
      seriesNo: 85,
    },
    {
      type: "small",
      seatId: "UG_S70",
      floor: "UG",
      seriesNo: 86,
    },
    {
      type: "small",
      seatId: "UG_S71",
      floor: "UG",
      seriesNo: 87,
    },
    {
      type: "small",
      colSpan: 2,
      seatId: "UG_S72",
      floor: "UG",
      seriesNo: 88,
    },
    {
      type: "small",
      colSpan: 2,
      seatId: "UG_S73",
      floor: "UG",
      seriesNo: 89,
    },
    {
      type: "small",
      colSpan: 2,
      seatId: "UG_S74",
      floor: "UG",
      seriesNo: 90,
    },
    {
      type: "small",
      seatId: "UG_S75",
      floor: "UG",
      seriesNo: 91,
    },
    {
      type: "small",
      seatId: "UG_S76",
      floor: "UG",
      seriesNo: 92,
    },
    {
      type: "small",
      seatId: "UG_S77",
      floor: "UG",
      seriesNo: 93,
    },
    {
      type: "small",
      seatId: "UG_S78",
      floor: "UG",
      seriesNo: 94,
    },
    {
      type: "small",
      colSpan: 2,
      seatId: "UG_S79",
      floor: "UG",
      seriesNo: 95,
    },
    {
      type: "small",
      colSpan: 2,
      seatId: "UG_S80",
      floor: "UG",
      seriesNo: 96,
    },
    {
      type: "small",
      colSpan: 2,
      seatId: "UG_S81",
      floor: "UG",
      seriesNo: 97,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 4,
      floor: "UG",
      seriesNo: 98,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 6,
      floor: "UG",
      seriesNo: 99,
    },
    {
      type: "small",
      seatId: "UG_S82",
      floor: "UG",
      seriesNo: 100,
    },
    {
      type: "small",
      seatId: "UG_S83",
      floor: "UG",
      seriesNo: 101,
    },
    {
      type: "small",
      seatId: "UG_S84",
      floor: "UG",
      seriesNo: 102,
    },
    {
      type: "small",
      seatId: "UG_S85",
      floor: "UG",
      seriesNo: 103,
    },
    {
      type: "path",
      colSpan: 6,
      floor: "UG",
      seriesNo: 104,
    },
    {
      type: "fixed",
      colSpan: 4,
      rowSpan: 3,
      disabled: true,
      label: "Admin Room",
      floor: "UG",
      seriesNo: 105,
    },
  ],
};

export const groundFloor = {
  numRows: 25,
  numCols: 13,

  rowData: [
    {
      type: "fixed",
      rowSpan: 3,
      colSpan: 3,
      label: "Papa G",
      disabled: true,
      seatId: 1,
      floor: "GF",
      seriesNo: 0,
    },
    {
      type: "path",
      rowSpan: 25,
      colSpan: 1,
      floor: "GF",
      seriesNo: 1,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "GF_S1",
      floor: "GF",
      seriesNo: 2,
    },
    {
      type: "small",
      seatId: "GF_S2",
      floor: "GF",
      seriesNo: 3,
    },
    {
      type: "small",
      seatId: "GF_S3",
      floor: "GF",
      seriesNo: 4,
    },
    {
      type: "small",
      seatId: "GF_S4",
      floor: "GF",
      seriesNo: 5,
    },
    {
      type: "path",
      rowSpan: 25,
      colSpan: 1,
      floor: "GF",
      seriesNo: 6,
    },
    {
      type: "fixed",
      rowSpan: 6,
      colSpan: 3,
      label: "Meeting Room",
      disabled: true,
      seatId: 6,
      floor: "GF",
      seriesNo: 7,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 5,
      floor: "GF",
      seriesNo: 8,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "GF_S5",
      floor: "GF",
      seriesNo: 9,
    },
    {
      type: "small",
      seatId: "GF_S6",
      floor: "GF",
      seriesNo: 10,
    },
    {
      type: "small",
      seatId: "GF_S7",
      floor: "GF",
      seriesNo: 11,
    },
    {
      type: "small",
      seatId: "GF_S8",
      floor: "GF",
      seriesNo: 12,
    },
    {
      type: "block",
      rowSpan: 4,
      colSpan: 3,
      seatId: "GF_B1",
      floor: "GF",
      seriesNo: 13,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "GF_S9",
      floor: "GF",
      seriesNo: 14,
    },
    {
      type: "small",
      seatId: "GF_S10",
      floor: "GF",
      seriesNo: 15,
    },
    {
      type: "small",
      seatId: "GF_S11",
      floor: "GF",
      seriesNo: 16,
    },
    {
      type: "small",
      seatId: "GF_S12",
      floor: "GF",
      seriesNo: 17,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 5,
      floor: "GF",
      seriesNo: 18,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "GF_S13",
      floor: "GF",
      seriesNo: 19,
    },
    {
      type: "small",
      seatId: "GF_S14",
      floor: "GF",
      seriesNo: 20,
    },
    {
      type: "small",
      seatId: "GF_S15",
      floor: "GF",
      seriesNo: 21,
    },
    {
      type: "small",
      seatId: "GF_S16",
      floor: "GF",
      seriesNo: 22,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "GF_S17",
      floor: "GF",
      seriesNo: 23,
    },
    {
      type: "small",
      seatId: "GF_S18",
      floor: "GF",
      seriesNo: 24,
    },
    {
      type: "small",
      seatId: "GF_S19",
      floor: "GF",
      seriesNo: 25,
    },
    {
      type: "small",
      seatId: "GF_S20",
      floor: "GF",
      seriesNo: 26,
    },
    {
      type: "block",
      rowSpan: 3,
      colSpan: 3,
      seatId: "GF_B2",
      floor: "GF",
      seriesNo: 27,
    },
    {
      type: "block",
      rowSpan: 2,
      colSpan: 3,
      seatId: "GF_B3",
      floor: "GF",
      seriesNo: 28,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 5,
      floor: "GF",
      seriesNo: 29,
    },
    {
      type: "small",
      seatId: "GF_S21",
      floor: "GF",
      seriesNo: 30,
    },
    {
      type: "small",
      seatId: "GF_S22",
      floor: "GF",
      seriesNo: 31,
    },
    {
      type: "small",
      seatId: "GF_S23",
      floor: "GF",
      seriesNo: 32,
    },
    {
      type: "small",
      seatId: "GF_S24",
      floor: "GF",
      seriesNo: 33,
    },
    {
      type: "small",
      seatId: "GF_S25",
      floor: "GF",
      seriesNo: 34,
    },
    {
      type: "block",
      rowSpan: 2,
      colSpan: 3,
      seatId: "GF_B4",
      floor: "GF",
      seriesNo: 35,
    },
    {
      type: "small",
      seatId: "GF_S26",
      floor: "GF",
      seriesNo: 36,
    },
    {
      type: "small",
      seatId: "GF_S27",
      floor: "GF",
      seriesNo: 37,
    },
    {
      type: "small",
      seatId: "GF_S28",
      floor: "GF",
      seriesNo: 38,
    },
    {
      type: "small",
      seatId: "GF_S29",
      floor: "GF",
      seriesNo: 39,
    },
    {
      type: "small",
      seatId: "GF_S30",
      floor: "GF",
      seriesNo: 40,
    },
    {
      type: "fixed",
      rowSpan: 2,
      colSpan: 3,
      label: "Meeting Room",
      disabled: true,
      seatId: 6,
      floor: "GF",
      seriesNo: 41,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 5,
      floor: "GF",
      seriesNo: 42,
    },
    {
      type: "small",
      seatId: "GF_S31",
      floor: "GF",
      seriesNo: 43,
    },
    {
      type: "small",
      seatId: "GF_S32",
      floor: "GF",
      seriesNo: 44,
    },
    {
      type: "small",
      seatId: "GF_S33",
      floor: "GF",
      seriesNo: 45,
    },
    {
      type: "small",
      seatId: "GF_S34",
      floor: "GF",
      seriesNo: 46,
    },
    {
      type: "small",
      seatId: "GF_S35",
      floor: "GF",
      seriesNo: 47,
    },
    {
      type: "small",
      seatId: "GF_S36",
      floor: "GF",
      seriesNo: 48,
    },
    {
      type: "small",
      seatId: "GF_S37",
      floor: "GF",
      seriesNo: 49,
    },
    {
      type: "small",
      seatId: "GF_S38",
      floor: "GF",
      seriesNo: 50,
    },
    {
      type: "small",
      seatId: "GF_S39",
      floor: "GF",
      seriesNo: 51,
    },
    {
      type: "small",
      seatId: "GF_S40",
      floor: "GF",
      seriesNo: 52,
    },
    {
      type: "small",
      seatId: "GF_S41",
      floor: "GF",
      seriesNo: 53,
    },
    {
      type: "small",
      seatId: "GF_S42",
      floor: "GF",
      seriesNo: 54,
    },
    {
      type: "small",
      seatId: "GF_S43",
      floor: "GF",
      seriesNo: 55,
    },
    {
      type: "small",
      seatId: "GF_S44",
      floor: "GF",
      seriesNo: 56,
    },
    {
      type: "small",
      seatId: "GF_S45",
      floor: "GF",
      seriesNo: 57,
    },
    {
      type: "small",
      seatId: "GF_S46",
      floor: "GF",
      seriesNo: 58,
    },
    {
      type: "small",
      seatId: "GF_S47",
      floor: "GF",
      seriesNo: 59,
    },
    {
      type: "small",
      seatId: "GF_S48",
      floor: "GF",
      seriesNo: 60,
    },
    {
      type: "small",
      seatId: "GF_S49",
      floor: "GF",
      seriesNo: 61,
    },
    {
      type: "small",
      seatId: "GF_S50",
      floor: "GF",
      seriesNo: 62,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "GF_S51",
      floor: "GF",
      seriesNo: 63,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 3,
      floor: "GF",
      seriesNo: 64,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 5,
      floor: "GF",
      seriesNo: 65,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 3,
      floor: "GF",
      seriesNo: 66,
    },
    {
      type: "small",
      seatId: "GF_S52",
      floor: "GF",
      seriesNo: 67,
    },
    {
      type: "small",
      seatId: "GF_S53",
      floor: "GF",
      seriesNo: 68,
    },
    {
      type: "small",
      seatId: "GF_S54",
      floor: "GF",
      seriesNo: 69,
    },
    {
      type: "small",
      seatId: "GF_S55",
      floor: "GF",
      seriesNo: 70,
    },
    {
      type: "small",
      seatId: "GF_S56",
      floor: "GF",
      seriesNo: 71,
    },
    {
      type: "small",
      seatId: "GF_S57",
      floor: "GF",
      seriesNo: 72,
    },
    {
      type: "small",
      seatId: "GF_S58",
      floor: "GF",
      seriesNo: 73,
    },
    {
      type: "small",
      seatId: "GF_S59",
      floor: "GF",
      seriesNo: 74,
    },
    {
      type: "small",
      seatId: "GF_S60",
      floor: "GF",
      seriesNo: 75,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "GF_S61",
      floor: "GF",
      seriesNo: 76,
    },
    {
      type: "small",
      seatId: "GF_S62",
      floor: "GF",
      seriesNo: 77,
    },
    {
      type: "small",
      seatId: "GF_S63",
      floor: "GF",
      seriesNo: 78,
    },
    {
      type: "small",
      seatId: "GF_S64",
      floor: "GF",
      seriesNo: 79,
    },
    {
      type: "small",
      seatId: "GF_S65",
      floor: "GF",
      seriesNo: 80,
    },
    {
      type: "small",
      seatId: "GF_S66",
      floor: "GF",
      seriesNo: 81,
    },
    {
      type: "small",
      seatId: "GF_S67",
      floor: "GF",
      seriesNo: 82,
    },
    {
      type: "small",
      seatId: "GF_S68",
      floor: "GF",
      seriesNo: 83,
    },
    {
      type: "small",
      seatId: "GF_S69",
      floor: "GF",
      seriesNo: 84,
    },
    {
      type: "small",
      seatId: "GF_S70",
      floor: "GF",
      seriesNo: 85,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "GF_S71",
      floor: "GF",
      seriesNo: 86,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 3,
      floor: "GF",
      seriesNo: 87,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 5,
      floor: "GF",
      seriesNo: 88,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 3,
      floor: "GF",
      seriesNo: 89,
    },
    {
      type: "small",
      seatId: "GF_S72",
      floor: "GF",
      seriesNo: 90,
    },
    {
      type: "small",
      seatId: "GF_S73",
      floor: "GF",
      seriesNo: 91,
    },
    {
      type: "small",
      seatId: "GF_S74",
      floor: "GF",
      seriesNo: 92,
    },
    {
      type: "small",
      seatId: "GF_S75",
      floor: "GF",
      seriesNo: 93,
    },
    {
      type: "small",
      seatId: "GF_S76",
      floor: "GF",
      seriesNo: 94,
    },
    {
      type: "small",
      seatId: "GF_S77",
      floor: "GF",
      seriesNo: 95,
    },
    {
      type: "small",
      seatId: "GF_S78",
      floor: "GF",
      seriesNo: 96,
    },
    {
      type: "small",
      seatId: "GF_S79",
      floor: "GF",
      seriesNo: 97,
    },
    {
      type: "small",
      seatId: "GF_S80",
      floor: "GF",
      seriesNo: 98,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "GF_S81",
      floor: "GF",
      seriesNo: 99,
    },
    {
      type: "small",
      seatId: "GF_S82",
      floor: "GF",
      seriesNo: 100,
    },
    {
      type: "small",
      seatId: "GF_S83",
      floor: "GF",
      seriesNo: 101,
    },
    {
      type: "small",
      seatId: "GF_S84",
      floor: "GF",
      seriesNo: 102,
    },
    {
      type: "fixed",
      rowSpan: 5,
      colSpan: 5,
      label: "Pantry",
      disabled: true,
      seatId: 6,
      floor: "GF",
      seriesNo: 103,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 3,
      floor: "GF",
      seriesNo: 104,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 3,
      floor: "GF",
      seriesNo: 105,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 3,
      floor: "GF",
      seriesNo: 106,
    },
    {
      type: "small",
      seatId: "GF_S85",
      floor: "GF",
      seriesNo: 107,
    },
    {
      type: "small",
      seatId: "GF_S86",
      floor: "GF",
      seriesNo: 108,
    },
    {
      type: "small",
      seatId: "GF_S87",
      floor: "GF",
      seriesNo: 109,
    },
    {
      type: "small",
      seatId: "GF_S88",
      floor: "GF",
      seriesNo: 110,
    },
    {
      type: "small",
      seatId: "GF_S89",
      floor: "GF",
      seriesNo: 111,
    },
    {
      type: "small",
      seatId: "GF_S90",
      floor: "GF",
      seriesNo: 112,
    },
    {
      type: "small",
      seatId: "GF_S91",
      floor: "GF",
      seriesNo: 113,
    },
    {
      type: "small",
      seatId: "GF_S92",
      floor: "GF",
      seriesNo: 114,
    },
    {
      type: "small",
      seatId: "GF_S93",
      floor: "GF",
      seriesNo: 115,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 3,
      floor: "GF",
      seriesNo: 116,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 3,
      floor: "GF",
      seriesNo: 117,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 3,
      floor: "GF",
      seriesNo: 118,
    },
    {
      type: "small",
      seatId: "GF_S94",
      floor: "GF",
      seriesNo: 119,
    },
    {
      type: "small",
      seatId: "GF_S95",
      floor: "GF",
      seriesNo: 120,
    },
    {
      type: "small",
      seatId: "GF_S96",
      floor: "GF",
      seriesNo: 121,
    },
  ],
};

export const firstFloor = {
  numRows: 34,
  numCols: 18,

  rowData: [
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S1",
      floor: "FF",
      seriesNo: 0,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S2",
      floor: "FF",
      seriesNo: 1,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S3",
      floor: "FF",
      seriesNo: 2,
    },
    {
      type: "fixed",
      rowSpan: 3,
      colSpan: 1,
      label: " ",
      disabled: true,
      floor: "FF",
      seriesNo: 3,
    },
    {
      type: "fixed",
      rowSpan: 3,
      colSpan: 4,
      label: "Meeting Room",
      disabled: true,
      floor: "FF",
      seriesNo: 4,
    },
    {
      type: "path",
      rowSpan: 34,
      colSpan: 1,
      floor: "FF",
      seriesNo: 5,
    },
    {
      type: "fixed",
      rowSpan: 3,
      colSpan: 6,
      label: "Lalit Sir Room",
      disabled: true,
      floor: "FF",
      seriesNo: 6,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 6,
      floor: "FF",
      seriesNo: 7,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S4",
      floor: "FF",
      seriesNo: 8,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S5",
      floor: "FF",
      seriesNo: 9,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S6",
      floor: "FF",
      seriesNo: 10,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S7",
      floor: "FF",
      seriesNo: 11,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S8",
      floor: "FF",
      seriesNo: 12,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S9",
      floor: "FF",
      seriesNo: 13,
    },
    {
      type: "fixed",
      rowSpan: 1,
      colSpan: 5,
      label: "CMD Area",
      disabled: true,
      floor: "FF",
      seriesNo: 14,
    },
    {
      type: "path",
      rowSpan: 5,
      colSpan: 6,
      label: "CMD Area",
      disabled: true,
      floor: "FF",
      seriesNo: 15,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 11,
      floor: "FF",
      seriesNo: 16,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S10",
      floor: "FF",
      seriesNo: 17,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S11",
      floor: "FF",
      seriesNo: 18,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S12",
      floor: "FF",
      seriesNo: 19,
    },
    {
      type: "path",
      rowSpan: 2,
      colSpan: 1,
      floor: "FF",
      seriesNo: 20,
    },
    {
      type: "path",
      rowSpan: 6,
      colSpan: 4,
      floor: "FF",
      seriesNo: 21,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 6,
      floor: "FF",
      seriesNo: 22,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S13",
      floor: "FF",
      seriesNo: 23,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S14",
      floor: "FF",
      seriesNo: 24,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S15",
      floor: "FF",
      seriesNo: 25,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S16",
      floor: "FF",
      seriesNo: 26,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S17",
      floor: "FF",
      seriesNo: 27,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S18",
      floor: "FF",
      seriesNo: 28,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S19",
      floor: "FF",
      seriesNo: 29,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S20",
      floor: "FF",
      seriesNo: 30,
    },
    {
      type: "fixed",
      rowSpan: 8,
      colSpan: 6,
      label: "Board Room",
      disabled: true,
      floor: "FF",
      seriesNo: 31,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 2,
      floor: "FF",
      seriesNo: 32,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S21",
      floor: "FF",
      seriesNo: 33,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 3,
      floor: "FF",
      seriesNo: 34,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S22",
      floor: "FF",
      seriesNo: 35,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S23",
      floor: "FF",
      seriesNo: 36,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S24",
      floor: "FF",
      seriesNo: 37,
    },
    {
      type: "path",
      rowSpan: 24,
      colSpan: 1,
      floor: "FF",
      seriesNo: 38,
    },
    {
      type: "path",
      colSpan: 6,
      rowSpan: 1,
      floor: "FF",
      seriesNo: 39,
    },
    {
      type: "path",
      colSpan: 4,
      rowSpan: 1,
      floor: "FF",
      seriesNo: 40,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S25",
      floor: "FF",
      seriesNo: 41,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S26",
      floor: "FF",
      seriesNo: 42,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S27",
      floor: "FF",
      seriesNo: 43,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S28",
      floor: "FF",
      seriesNo: 44,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S29",
      floor: "FF",
      seriesNo: 45,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S30",
      floor: "FF",
      seriesNo: 46,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S31",
      floor: "FF",
      seriesNo: 47,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S32",
      floor: "FF",
      seriesNo: 48,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S33",
      floor: "FF",
      seriesNo: 49,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S34",
      floor: "FF",
      seriesNo: 50,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S35",
      floor: "FF",
      seriesNo: 51,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S36",
      floor: "FF",
      seriesNo: 52,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S37",
      floor: "FF",
      seriesNo: 53,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S38",
      floor: "FF",
      seriesNo: 54,
    },
    {
      type: "path",
      colSpan: 6,
      rowSpan: 1,
      floor: "FF",
      seriesNo: 55,
    },
    {
      type: "path",
      colSpan: 4,
      rowSpan: 1,
      floor: "FF",
      seriesNo: 56,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S39",
      floor: "FF",
      seriesNo: 57,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S40",
      floor: "FF",
      seriesNo: 58,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S41",
      floor: "FF",
      seriesNo: 59,
    },
    {
      type: "path",
      colSpan: 4,
      rowSpan: 2,
      floor: "FF",
      seriesNo: 60,
    },
    {
      type: "path",
      colSpan: 6,
      rowSpan: 1,
      floor: "FF",
      seriesNo: 61,
    },
    {
      type: "block",
      rowSpan: 2,
      colSpan: 6,
      seatId: "FF_B1",
      floor: "FF",
      seriesNo: 62,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "FF_S42",
      floor: "FF",
      seriesNo: 63,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "FF_S43",
      floor: "FF",
      seriesNo: 64,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S44",
      floor: "FF",
      seriesNo: 65,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S45",
      floor: "FF",
      seriesNo: 66,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S46",
      floor: "FF",
      seriesNo: 67,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S47",
      floor: "FF",
      seriesNo: 68,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "FF_S48",
      floor: "FF",
      seriesNo: 69,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "FF_S49",
      floor: "FF",
      seriesNo: 70,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S50",
      floor: "FF",
      seriesNo: 71,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S51",
      floor: "FF",
      seriesNo: 72,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S52",
      floor: "FF",
      seriesNo: 73,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S53",
      floor: "FF",
      seriesNo: 74,
    },
    {
      type: "block",
      rowSpan: 6,
      colSpan: 6,
      seatId: "FF_B2",
      floor: "FF",
      seriesNo: 75,
    },
    {
      type: "path",
      colSpan: 6,
      rowSpan: 1,
      floor: "FF",
      seriesNo: 76,
    },
    {
      type: "path",
      colSpan: 4,
      rowSpan: 4,
      floor: "FF",
      seriesNo: 77,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "FF_S54",
      floor: "FF",
      seriesNo: 78,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "FF_S55",
      floor: "FF",
      seriesNo: 79,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "FF_S56",
      floor: "FF",
      seriesNo: 80,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "FF_S57",
      floor: "FF",
      seriesNo: 81,
    },
    {
      type: "path",
      colSpan: 6,
      rowSpan: 1,
      floor: "FF",
      seriesNo: 82,
    },
    {
      type: "path",
      colSpan: 6,
      rowSpan: 1,
      floor: "FF",
      seriesNo: 83,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S58",
      floor: "FF",
      seriesNo: 84,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S59",
      floor: "FF",
      seriesNo: 85,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S60",
      floor: "FF",
      seriesNo: 86,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S61",
      floor: "FF",
      seriesNo: 87,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S62",
      floor: "FF",
      seriesNo: 88,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S63",
      floor: "FF",
      seriesNo: 89,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S64",
      floor: "FF",
      seriesNo: 90,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S65",
      floor: "FF",
      seriesNo: 91,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S66",
      floor: "FF",
      seriesNo: 92,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S67",
      floor: "FF",
      seriesNo: 93,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S68",
      floor: "FF",
      seriesNo: 94,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "FF_S69",
      floor: "FF",
      seriesNo: 95,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "FF_S70",
      floor: "FF",
      seriesNo: 96,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 6,
      floor: "FF",
      seriesNo: 97,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 4,
      floor: "FF",
      seriesNo: 98,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 6,
      floor: "FF",
      seriesNo: 99,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S71",
      floor: "FF",
      seriesNo: 100,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S72",
      floor: "FF",
      seriesNo: 101,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S73",
      floor: "FF",
      seriesNo: 102,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S74",
      floor: "FF",
      seriesNo: 103,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S75",
      floor: "FF",
      seriesNo: 104,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S76",
      floor: "FF",
      seriesNo: 105,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S77",
      floor: "FF",
      seriesNo: 106,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "FF_S78",
      floor: "FF",
      seriesNo: 107,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "FF_S79",
      floor: "FF",
      seriesNo: 108,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S80",
      floor: "FF",
      seriesNo: 109,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 2,
      floor: "FF",
      seriesNo: 110,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S81",
      floor: "FF",
      seriesNo: 111,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S82",
      floor: "FF",
      seriesNo: 112,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S83",
      floor: "FF",
      seriesNo: 113,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S84",
      floor: "FF",
      seriesNo: 114,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S85",
      floor: "FF",
      seriesNo: 115,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S86",
      floor: "FF",
      seriesNo: 116,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S87",
      floor: "FF",
      seriesNo: 117,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S88",
      floor: "FF",
      seriesNo: 118,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 6,
      floor: "FF",
      seriesNo: 119,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 4,
      floor: "FF",
      seriesNo: 120,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 6,
      floor: "FF",
      seriesNo: 121,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S89",
      floor: "FF",
      seriesNo: 122,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S90",
      floor: "FF",
      seriesNo: 123,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S91",
      floor: "FF",
      seriesNo: 124,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S92",
      floor: "FF",
      seriesNo: 125,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S93",
      floor: "FF",
      seriesNo: 126,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S94",
      floor: "FF",
      seriesNo: 127,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S95",
      floor: "FF",
      seriesNo: 128,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S96",
      floor: "FF",
      seriesNo: 129,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S97",
      floor: "FF",
      seriesNo: 130,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "FF_S98",
      floor: "FF",
      seriesNo: 131,
    },
    {
      type: "fixed",
      rowSpan: 3,
      colSpan: 6,
      disabled: true,
      label: "Meeting Room",
      floor: "FF",
      seriesNo: 132,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S99",
      floor: "FF",
      seriesNo: 133,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S100",
      floor: "FF",
      seriesNo: 134,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S101",
      floor: "FF",
      seriesNo: 135,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S102",
      floor: "FF",
      seriesNo: 136,
    },
    {
      type: "fixed",
      rowSpan: 3,
      colSpan: 6,
      disabled: true,
      label: "Server",
      floor: "FF",
      seriesNo: 137,
    },
    {
      type: "fixed",
      rowSpan: 3,
      colSpan: 1,
      disabled: true,
      label: "Pantry",
      floor: "FF",
      seriesNo: 138,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S103",
      floor: "FF",
      seriesNo: 139,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S104",
      floor: "FF",
      seriesNo: 140,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S105",
      floor: "FF",
      seriesNo: 141,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S106",
      floor: "FF",
      seriesNo: 142,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S107",
      floor: "FF",
      seriesNo: 143,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "FF_S108",
      floor: "FF",
      seriesNo: 144,
    },
  ],
};

export const secondFloor = {
  numCols: 21,
  numRows: 24,

  rowData: [
    {
      type: "path",
      rowSpan: 3,
      colSpan: 1,
      floor: "SF",
      seriesNo: 0,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S1",
      floor: "SF",
      seriesNo: 1,
    },
    {
      type: "path",
      rowSpan: 3,
      colSpan: 1,
      floor: "SF",
      seriesNo: 2,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S2",
      floor: "SF",
      seriesNo: 3,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S3",
      floor: "SF",
      seriesNo: 4,
    },
    {
      type: "path",
      rowSpan: 3,
      colSpan: 1,
      floor: "SF",
      seriesNo: 5,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S4",
      floor: "SF",
      seriesNo: 6,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S5",
      floor: "SF",
      seriesNo: 7,
    },
    {
      type: "path",
      rowSpan: 3,
      colSpan: 6,
      floor: "SF",
      seriesNo: 8,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S6",
      floor: "SF",
      seriesNo: 9,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S7",
      floor: "SF",
      seriesNo: 10,
    },
    {
      type: "path",
      rowSpan: 3,
      colSpan: 1,
      floor: "SF",
      seriesNo: 11,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S8",
      floor: "SF",
      seriesNo: 12,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S9",
      floor: "SF",
      seriesNo: 13,
    },
    {
      type: "path",
      rowSpan: 3,
      colSpan: 1,
      floor: "SF",
      seriesNo: 14,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S10",
      floor: "SF",
      seriesNo: 15,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S11",
      floor: "SF",
      seriesNo: 16,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S12",
      floor: "SF",
      seriesNo: 17,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S13",
      floor: "SF",
      seriesNo: 18,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S14",
      floor: "SF",
      seriesNo: 19,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S15",
      floor: "SF",
      seriesNo: 20,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S16",
      floor: "SF",
      seriesNo: 21,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S17",
      floor: "SF",
      seriesNo: 22,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S18",
      floor: "SF",
      seriesNo: 23,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S19",
      floor: "SF",
      seriesNo: 24,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S20",
      floor: "SF",
      seriesNo: 25,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S21",
      floor: "SF",
      seriesNo: 26,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S22",
      floor: "SF",
      seriesNo: 27,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S23",
      floor: "SF",
      seriesNo: 28,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S24",
      floor: "SF",
      seriesNo: 29,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S25",
      floor: "SF",
      seriesNo: 30,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S26",
      floor: "SF",
      seriesNo: 31,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S27",
      floor: "SF",
      seriesNo: 32,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S28",
      floor: "SF",
      seriesNo: 33,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S29",
      floor: "SF",
      seriesNo: 34,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S30",
      floor: "SF",
      seriesNo: 35,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 8,
      floor: "SF",
      seriesNo: 36,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 13,
      floor: "SF",
      seriesNo: 37,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S31",
      floor: "SF",
      seriesNo: 38,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S32",
      floor: "SF",
      seriesNo: 39,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S33",
      floor: "SF",
      seriesNo: 40,
    },
    {
      type: "path",
      rowSpan: 21,
      colSpan: 1,
      floor: "SF",
      seriesNo: 41,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 11,
      floor: "SF",
      seriesNo: 42,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S34",
      floor: "SF",
      seriesNo: 43,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S35",
      floor: "SF",
      seriesNo: 44,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S36",
      floor: "SF",
      seriesNo: 45,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S37",
      floor: "SF",
      seriesNo: 46,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S38",
      floor: "SF",
      seriesNo: 47,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S39",
      floor: "SF",
      seriesNo: 48,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S40",
      floor: "SF",
      seriesNo: 49,
    },
    {
      type: "path",
      rowSpan: 20,
      colSpan: 1,
      floor: "SF",
      seriesNo: 50,
    },
    {
      type: "block",
      rowSpan: 3,
      colSpan: 6,
      seatId: "SF_B1",
      floor: "SF",
      seriesNo: 51,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 9,
      floor: "SF",
      seriesNo: 52,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 4,
      floor: "SF",
      seriesNo: 53,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S41",
      floor: "SF",
      seriesNo: 54,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S42",
      floor: "SF",
      seriesNo: 55,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S43",
      floor: "SF",
      seriesNo: 56,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S44",
      floor: "SF",
      seriesNo: 57,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S45",
      floor: "SF",
      seriesNo: 58,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S46",
      floor: "SF",
      seriesNo: 59,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S47",
      floor: "SF",
      seriesNo: 60,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S48",
      floor: "SF",
      seriesNo: 61,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S49",
      floor: "SF",
      seriesNo: 62,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S50",
      floor: "SF",
      seriesNo: 63,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S51",
      floor: "SF",
      seriesNo: 64,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S52",
      floor: "SF",
      seriesNo: 65,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S53",
      floor: "SF",
      seriesNo: 66,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S54",
      floor: "SF",
      seriesNo: 67,
    },
    {
      type: "block",
      rowSpan: 3,
      colSpan: 6,
      seatId: "SF_B2",
      floor: "SF",
      seriesNo: 68,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 9,
      floor: "SF",
      seriesNo: 69,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 4,
      floor: "SF",
      seriesNo: 70,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S55",
      floor: "SF",
      seriesNo: 71,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S56",
      floor: "SF",
      seriesNo: 72,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S57",
      floor: "SF",
      seriesNo: 73,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S58",
      floor: "SF",
      seriesNo: 74,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S59",
      floor: "SF",
      seriesNo: 75,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S60",
      floor: "SF",
      seriesNo: 76,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S61",
      floor: "SF",
      seriesNo: 77,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S62",
      floor: "SF",
      seriesNo: 78,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S63",
      floor: "SF",
      seriesNo: 79,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S64",
      floor: "SF",
      seriesNo: 80,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S65",
      floor: "SF",
      seriesNo: 81,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S66",
      floor: "SF",
      seriesNo: 82,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S67",
      floor: "SF",
      seriesNo: 83,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S68",
      floor: "SF",
      seriesNo: 84,
    },
    {
      type: "block",
      rowSpan: 3,
      colSpan: 6,
      seatId: "SF_B3",
      floor: "SF",
      seriesNo: 85,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 9,
      floor: "SF",
      seriesNo: 86,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 4,
      floor: "SF",
      seriesNo: 87,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S69",
      floor: "SF",
      seriesNo: 88,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S70",
      floor: "SF",
      seriesNo: 89,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S71",
      floor: "SF",
      seriesNo: 90,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S72",
      floor: "SF",
      seriesNo: 91,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S73",
      floor: "SF",
      seriesNo: 92,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S74",
      floor: "SF",
      seriesNo: 93,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S75",
      floor: "SF",
      seriesNo: 94,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 9,
      floor: "SF",
      seriesNo: 95,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S76",
      floor: "SF",
      seriesNo: 96,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S77",
      floor: "SF",
      seriesNo: 97,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S78",
      floor: "SF",
      seriesNo: 98,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S79",
      floor: "SF",
      seriesNo: 99,
    },
    {
      type: "path",
      rowSpan: 2,
      colSpan: 6,
      floor: "SF",
      seriesNo: 100,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 9,
      floor: "SF",
      seriesNo: 101,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 4,
      floor: "SF",
      seriesNo: 102,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S80",
      floor: "SF",
      seriesNo: 103,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S81",
      floor: "SF",
      seriesNo: 104,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S82",
      floor: "SF",
      seriesNo: 105,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S83",
      floor: "SF",
      seriesNo: 106,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S84",
      floor: "SF",
      seriesNo: 107,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S85",
      floor: "SF",
      seriesNo: 108,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S86",
      floor: "SF",
      seriesNo: 109,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S87",
      floor: "SF",
      seriesNo: 110,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S88",
      floor: "SF",
      seriesNo: 111,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S89",
      floor: "SF",
      seriesNo: 112,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S90",
      floor: "SF",
      seriesNo: 113,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S91",
      floor: "SF",
      seriesNo: 114,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S92",
      floor: "SF",
      seriesNo: 115,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S93",
      floor: "SF",
      seriesNo: 116,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S94",
      floor: "SF",
      seriesNo: 117,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S95",
      floor: "SF",
      seriesNo: 118,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S96",
      floor: "SF",
      seriesNo: 119,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S97",
      floor: "SF",
      seriesNo: 120,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 9,
      floor: "SF",
      seriesNo: 121,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 4,
      floor: "SF",
      seriesNo: 122,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 6,
      floor: "SF",
      seriesNo: 123,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S98",
      floor: "SF",
      seriesNo: 124,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S99",
      floor: "SF",
      seriesNo: 125,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S100",
      floor: "SF",
      seriesNo: 126,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S101",
      floor: "SF",
      seriesNo: 127,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S102",
      floor: "SF",
      seriesNo: 128,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S103",
      floor: "SF",
      seriesNo: 129,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S104",
      floor: "SF",
      seriesNo: 130,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "SF_S105",
      floor: "SF",
      seriesNo: 131,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "SF_S106",
      floor: "SF",
      seriesNo: 132,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "SF_S107",
      floor: "SF",
      seriesNo: 133,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S108",
      floor: "SF",
      seriesNo: 134,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S109",
      floor: "SF",
      seriesNo: 135,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S110",
      floor: "SF",
      seriesNo: 136,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S111",
      floor: "SF",
      seriesNo: 137,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S112",
      floor: "SF",
      seriesNo: 138,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S113",
      floor: "SF",
      seriesNo: 139,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S114",
      floor: "SF",
      seriesNo: 140,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "SF_S115",
      floor: "SF",
      seriesNo: 141,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "SF_S116",
      floor: "SF",
      seriesNo: 142,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "SF_S117",
      floor: "SF",
      seriesNo: 143,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 9,
      floor: "SF",
      seriesNo: 144,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 4,
      floor: "SF",
      seriesNo: 145,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 6,
      floor: "SF",
      seriesNo: 146,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S118",
      floor: "SF",
      seriesNo: 147,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S119",
      floor: "SF",
      seriesNo: 148,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S120",
      floor: "SF",
      seriesNo: 149,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S121",
      floor: "SF",
      seriesNo: 150,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S122",
      floor: "SF",
      seriesNo: 151,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S123",
      floor: "SF",
      seriesNo: 152,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S124",
      floor: "SF",
      seriesNo: 153,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "SF_S125",
      floor: "SF",
      seriesNo: 154,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "SF_S126",
      floor: "SF",
      seriesNo: 155,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "SF_S127",
      floor: "SF",
      seriesNo: 156,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S128",
      floor: "SF",
      seriesNo: 157,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S129",
      floor: "SF",
      seriesNo: 158,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S130",
      floor: "SF",
      seriesNo: 159,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S131",
      floor: "SF",
      seriesNo: 160,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S132",
      floor: "SF",
      seriesNo: 161,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S133",
      floor: "SF",
      seriesNo: 162,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 1,
      seatId: "SF_S134",
      floor: "SF",
      seriesNo: 163,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "SF_S135",
      floor: "SF",
      seriesNo: 164,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "SF_S136",
      floor: "SF",
      seriesNo: 165,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 2,
      seatId: "SF_S137",
      floor: "SF",
      seriesNo: 166,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 9,
      floor: "SF",
      seriesNo: 167,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 4,
      floor: "SF",
      seriesNo: 168,
    },
    {
      type: "path",
      rowSpan: 1,
      colSpan: 6,
      floor: "SF",
      seriesNo: 169,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S138",
      floor: "SF",
      seriesNo: 170,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S139",
      floor: "SF",
      seriesNo: 171,
    },
    {
      type: "small",
      rowSpan: 1,
      colSpan: 3,
      seatId: "SF_S140",
      floor: "SF",
      seriesNo: 172,
    },
  ],
};
